### PR TITLE
Add -h for help page

### PR DESCRIPTION
**Pull request by sebix**

### CODE REVIEW

**Comment by Olf0** [comment]
Thanks for the PR, but see https://github.com/Olf0/sfos-upgrade/commit/c9a6c16ac24de7b61dc007ada02d7144658332a9
I deliberately freed the option `-h` to mean other things: The standard set of help options is `-?` as a single letter option and `--help` as a long-opt.

Although it is questionable if I ever get around to use `-h`, I do have ideas what to use it for.

**Comment by sebix** [comment]
> Although it is questionable if I ever get around to use `-h`, I do have ideas what to use it for.

Please don't use `-h` for something else. `-h` is widely known for the help page, misusing it is only confusing and in the worst case harmful.

**Comment by Olf0** [comment]
> Please don't use `-h` for something else. `-h` is widely known for the help page, misusing it is only confusing and in the worst case harmful.

I will take your opinion into consideration, though I cannot concur with your statement: It is `-?` as a short option and `--help` as a long option which by convention mean "help".
`-h` often means "human readable" (e.g. for `df`, `du`, `ls` etc.) or something else.

**Comment by sebix** [comment]
> `-h` often means "human readable" (e.g. for `df`, `du`, `ls` etc.) or something else.

As long as `-h` is not an action :)

**Pull request closed without merging**
